--- 
- hosts: all 
  become: yes
  tasks: 
          
          - name: i want install web
            apt:
             
                   name: apache2
                   state: present 

          - name: i want start/stop on ubuntu
            service:

                   name: apache2
                   state: stopped        